routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index')->name('index');
Route::get('memberIndex', 'IndexController@memberIndex')->name('memberIndex');
Route::get('setSchool/{id}', 'IndexController@setSchool')->name('setSchool');
Route::get('search', 'IndexController@search')->name('search');

//登录注册
Route::get('register', 'PassportController@showRegisterForm')->name('passport.register');
Route::post('register', 'PassportController@register')->name('passport.register');
Route::get('login', 'PassportController@showLoginForm')->name('passport.login');
Route::post('login', 'PassportController@login')->name('passport.login');
Route::get('logout', 'PassportController@logout')->name('passport.logout');
Route::get('forgot', 'PassportController@showForgotForm')->name('passport.forgot');
Route::post('forgot', 'PassportController@forgot')->name('passport.forgot');

//个人信息
Route::get('user', 'UserController@index')->name('user.index');
Route::prefix('user')->group(function (){
    Route::get('avatar', 'UserController@avatar')->name('user.avatar');
    Route::post('avatar', 'UserController@updateAvatar')->name('user.avatar');
    Route::get('name', 'UserController@name')->name('user.name');
    Route::post('name', 'UserController@updateName')->name('user.name');
    Route::post('gander', 'UserController@updateGender')->name('user.gender');
    Route::post('school', 'USerController@updateSchool')->name('user.school');
});

//书本
Route::get('books/list', 'BooksController@list')->name('books.list');
Route::get('books/my', 'BooksController@my')->name('books.my');
Route::post('upload_image', 'BooksController@uploadImage')->name('books.upload_image');
Route::get('books/show-self/{book}', 'BooksController@showSelf')->name('books.show_self');//注意此处是一个隐式绑定
Route::get('books/toggle_show', 'BooksController@toggleShow')->name('books.toggle_show');
Route::resource('books', 'BooksController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);
//前端图片裁剪
Route::get('photo_clip', 'BooksController@photo_clip')->name('photo_clip');

//订单
Route::prefix('order')->group(function (){
    Route::get('create/{book}', 'OrdersController@create')->name('order.create');
    Route::post('store', 'OrdersController@store')->name('order.store');
    //列表
    Route::get('index', 'OrdersController@index')->name('order.index');
    Route::get('seller/index', 'OrdersController@sellerIndex')->name('order.seller_index');
    //详情
    Route::get('show/{order}', 'OrdersController@show')->name('order.show');
    Route::get('seller/show/{order}', 'OrdersController@sellerShow')->name('order.seller_show');
    //操作
    Route::get('pay/{order}' ,'OrdersController@pay')->name('order.pay');//发起支付
    Route::get('fake_pay', 'OrdersController@fakePay')->name('order.fake_pay');//模拟支付成功
    Route::get('confirm/{order}', 'OrdersController@confirm')->name('order.confirm');//卖家确认
    Route::get('send/{order}', 'OrdersController@send')->name('order.send');//卖家送达
    Route::get('get/{order}', 'OrdersController@get')->name('order.get');//买家取书
    Route::get('cancel/{order}', 'OrdersController@cancel')->name('order.cancel');//买家取消
});

//消息
Route::resource('notifications', 'NotificationsController', ['only' => ['index']]);

//提现
Route::resource('transfers', 'TransfersController', ['only' => ['create', 'store']]);

//资金
Route::get('account', 'AccountsController@index')->name('account.index');
Route::get('account/logs', 'AccountsController@logs')->name('account.logs');

//文章
Route::get('article/{article}/show', 'ArticlesController@show')->name('article.show');

app/Models/Book.php
<?php

namespace App\Models;
use Laravel\Scout\Searchable;

class Book extends Model
{
    use Searchable;

    protected $fillable = ['sn', 'name', 'image', 'author', 'press', 'published_at', 'used', 'original_price', 'price', 'description', 'status', 'is_show', 'is_recommend', 'user_id', 'category_id', 'school_id', 'admin_id'];

    public function school(){
        return $this->belongsTo(School::class);
    }

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function category(){
        return $this->belongsTo(Category::class);
    }

    public function orders(){
        return $this->hasMany(Order::class);
    }

    public function getUsedFormatAttribute(){
        $used_arr = config('custom.book.used');
        return $used_arr[$this->used];
    }

    public function getStatusNameAttribute(){
        $statuses = array_pluck(config('custom.book.status'), 'name', 'id');
        return $statuses[$this->status];
    }

    public function getAuthorAttribute($val){
        return $val ? $val : '佚名';
    }

    public function getPublishedAtAttribute($val)
    {
        return $val ? $val : '未知';
    }

    public function scopeOfSchool($query){
        return $query->where('school_id', session('school_id', 0));
    }

    public function scopeForUser($query){
        return $query->where('is_show', 1)->where('status', 2);
    }

    //是否可以被购买
    public function canBuy(){
        $statuses = array_pluck(config('custom.book.status'), 'canShow', 'id');
        return $statuses[$this->status];
    }

    //支付成功
    public function payed(){
        $this->status = 4;
        $this->save();
    }


    //推荐
    public function recommend(){
        return $this->ofSchool()
            ->forUser()
            ->where('is_recommend', 1)
            ->get();
    }
}

app/Http/Controllers/BooksController.php
<?php

namespace App\Http\Controllers;

use App\Handlers\ImageUploadHandler;
use App\Models\Book;
use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\BookRequest;
use Auth;

class BooksController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['index', 'show', 'list']]);
    }

    public function list(){
        $categories = Category::all();
        return view('books.list', compact('categories'));
    }

    /**
     * 异步读取列表
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
	public function index(Request $request)
	{
	    $category_id = $request->category_id;
		$books = Book::ofSchool()
            ->forUser()
            ->when($category_id, function ($query) use ($category_id){
		        return $query->where('category_id', $category_id);
            })
            ->orderBy(
            $request->input('orderBy', 'updated_at'),
            $request->input('orderType', 'desc')
        )->paginate(6);
		return view('books.index', compact('books'));
	}

	public function my(Request $request){
        $user = Auth::user();
        $mybooks = $user->books()
            ->when($request->status, function ($query) use ($request){
                return $query->where('status', $request->status);
            })
            ->orderBy('created_at', 'desc')->get();
        $statuses = config('custom.book.status');
        return view('books.my', compact('statuses', 'mybooks'));
    }

    /**
     * 书本首页
     * @param Book $book
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Book $book)
    {
        $user = $book->user;
        return view('books.show', compact('book', 'user'));
    }

	public function create(Book $book)
	{
	    $categories = Category::all();
	    $useds = config('custom.book.used');
		return view('books.create_and_edit', compact( 'book', 'categories', 'useds'));
	}

	public function uploadImage(Request $request, ImageUploadHandler $uploader){
        $data = [
            'code'=>0,
            'msg'=>'上传失败！',
            'file_path'=>'',
        ];
        // 判断是否有上传文件，并赋值给 $file
        if ($request->has('base_image')) {
            // 保存图片到本地
            $result = $uploader->saveBase($request->base_image, 'books', \Auth::id());
            // 图片保存成功的话
            if ($result) {
                $data['file_path'] = $result['path'];
                $data['msg'] = "上传成功!";
                $data['code'] = 1;
            }
        }
        return $data;
    }

	public function store(BookRequest $request, Book $book)
	{
		$book->fill($request->all());
		$book->user_id = Auth::id();
		$book->school_id = session('school_id');
		$book->save();
		return redirect()->route('books.show_self', $book->id)->with('message', '发布成功！请注意审核通知');
	}

	public function showSelf(Book $book){
        if($book->status == 3){
            session()->flash('danger', $book->admin_note);
        }
        return view('books.show_self', compact('book'));
    }

	public function edit(Book $book)
	{
        $this->authorize('update', $book);
        $categories = Category::all();
        $useds = config('custom.book.used');
		return view('books.create_and_edit', compact('book', 'categories', 'useds'));
	}

	public function update(BookRequest $request, Book $book)
	{
		$this->authorize('update', $book);
		$book->fill($request->all());
		$book->status = 1;
		$book->save();
		return redirect()->route('books.show_self', $book->id)->with('message', '编辑成功！请注意审核通知');
	}

	public function photo_clip(){
        return view('books.photo_clip');
    }

	public function toggleShow(Request $request){
        $id = $request->id;
        $book = Book::find($id);
        $this->authorize('toggleShow', $book);
        if($book->is_show == 1){
            $book->is_show = 2;
        }else{
            $book->is_show = 1;
        }
        $book->save();
        return ['status'=>1];
    }

	public function destroy(Book $book)
	{
		$this->authorize('destroy', $book);
		$book->delete();
		return redirect()->route('books.my')->with('message', '删除成功！');
	}
}

resources/views/books/create_and_edit.blade.php
@extends('layouts.app')
@section('body', '')
@section('css')
<style>
    .layui-upload-file {display: none;}
</style>
@endsection
@section('content')
<header class="comhead">
    @if($book->id)
        <h2>编辑图书</h2>
    @else
        <h2>发布图书</h2>
    @endif
    <a onclick="layer.confirm('书本未保存确认退出？', function (){location.href='@if($book->id){{ route('books.show_self', $book->id) }}@else{{ route('index') }}@endif'})" class="back"></a>
</header>
<div class="comheadbg"></div>
@include('public._errors')
@if($book->id)
    <form action="{{ route('books.update', $book->id) }}" method="post" accept-charset="UTF-8" enctype="multipart/form-data">
        <input type="hidden" name="_method" value="PUT">
        @else
            <form action="{{ route('books.store') }}" method="post" accept-charset="UTF-8" enctype="multipart/form-data">
                @endif
                {{ csrf_field() }}
<p class="rel_tit"><span>ISBN：</span><input type="text" placeholder="请输入ISBM码" name="sn" value="{{ old('sn', $book->sn) }}" /></p>
<div class="clear h02"></div>
<section class="rel_img">
    <p id="upload_image" class="img" style="background-image: url(/images/fm.png)">
        <img src="{{ old('image', $book->image) }}" id="image_show">
    </p>
    <input type="hidden" name="image" id="image" value="{{ old('image', $book->image) }}">
    <div class="box">
        <p><span>书名：</span><input type="text" name="name" class="text" placeholder="请输入书名" value="{{ old('name', $book->name) }}" /></p>
        <p><span>作者：</span><input type="text" name="author" class="text" placeholder="请输入作者" value="{{ old('author', $book->author) }}"/></p>
        <p><span>出版社：</span><input type="text" name="press" class="text text01" placeholder="请输入出版社" value="{{ old('press', $book->press) }}" /></p>
        <p><span>出版年份：</span><input type="text" style="width: 2.4rem;" name="published_at" class="text text02" placeholder="例如：2005" value="{{ old('published_at', $book->published_at) }}"/></p>
    </div>
</section>
<div class="clear h02"></div>
<section class="rel_info">
    <div class="a1">
        <span>新旧：</span>
        <select name="used">
            <option value="0">请选择新旧程度</option>
            @foreach ($useds as $key => $used)
                <option value="{{ $key }}" @if($book->used == $key) selected @endif>{{ $used }}</option>
            @endforeach
        </select>
    </div>
    <div class="a1">
        <span>分类：</span>
        <select name="category_id">
            <option value="0">请选择分类</option>
            @foreach ($categories as $category)
                <option value="{{ $category->id }}" @if($book->category_id == $category->id) selected @endif >{{ $category->name }}</option>
            @endforeach
        </select>
    </div>
    <p class="p1">
        <span>原价：</span><input type="text" name="original_price" class="text" value="{{ old('original_price', $book->original_price) }}" />
        <span>出售价：</span><input type="text" name="price" class="text" value="{{ old('price', $book->price) }}" />
    </p>
    <p class="p2">
        <span>图书描述：</span>
    </p>
    <textarea name="description" class="textarea" placeholder="请输入书本描述">{{ old('description', $book->description) }}</textarea>
</section>
<div class="clear h02"></div>
@if($book->id)
<div style="margin-left: 0.3rem; font-size: 0.24rem;color: #999;">内容修改之后需要等待重新审核</div>
@endif
<input type="submit" value="@if($book->id)保存修改@else发布书本@endif" class="bluebtn" />
<div class="clear h02"></div>
</form>
@include('layouts._footer')


@section('script')
    <script type="text/javascript">
        winCloseMyWin(".winbgclick");//关闭窗口

        function openPhotoClip(_url, _success, _cancel){
            layer.open({
                id:'photo_clip',
                title: '截取图片',
                type:2,
                anim:2,
                // shadeClose: true,
                area:['100%', '100%'],
                offset: '0px',
                content:_url,
                success: _success,
                cancel: _cancel,
            });
        }

        function book(base_image){
            var _load = layer.load();
            $.ajax({
                url:'{{ route('books.upload_image') }}',
                data:{'base_image':base_image},
                type:'post',
                success:function (data){
                    if(data.code === 1){
                        $('#image_show').attr('src', data.file_path);
                        $('#image').val(data.file_path);
                        layer.msg('上传成功');
                    }else{
                        layer.msg('上传失败');
                    }
                    layer.close(_load);
                }
            });
        }

        $(function (){
            $('#upload_image').click(function (){
                openPhotoClip('{{ route('photo_clip', ['size'=>'[640,880]' ,'fn'=>'book']) }}');
            });
        })



    </script>
@endsection

resources/views/books/index.blade.php
@if(count($books))
    @foreach ($books as $book)
    <a class="prolist" href="{{ route('books.show', [$book->id]) }}">
        <div class="box">
            <i style="background-image: url({{ $book->image }})"></i>
            <p class="p1">{{ $book->name }}</p>
            <p class="p2">{{ $book->author }}<span>{{ $book->press }}</span></p>
            <p class="p3">￥{{ $book->price }}<span>￥{{ $book->original_price }}</span></p>
            <p class="p4">
                <span class="sp1">{{ $book->published_at }}年出版</span><span class="sp2">{{ $book->used_format }}</span>
            </p>
        </div>
    </a>
    @endforeach
@endif

resources/views/books/list.blade.php
@extends('layouts.app')
@section('body', '')
@section('content')
@include('layouts._set_school')
<header class="comhead">
    <a href="{{ route('index') }}" class="back"></a>
    <div class="box01" style="width: 5.5rem;" onclick="location.href='{{ route('search') }}?focus=1'">
        <input type="submit" value=" " class="sub"  />
        <input type="search" value="" class="text" placeholder="输入关键词" readonly />
    </div>
</header>
<div class="comheadbg"></div>

<div class="slidingtit" id="slidingtit">
    <menu id="categories_box">
        <p><a href="{{ Request::url() }}">全部</a></p>
        @foreach($categories as $key => $category)
        <p><a href="{{ Request::url() }}?category_id={{ $category->id }}&index={{ $key + 1 }}">{{ $category->name }}</a></p>
        @endforeach
    </menu>
</div>

<div class="clear h10"></div>
<div class="class_tit" id="order_box">
    <a class="sel02" order_by="updated_at" order_type="desc"><span>最近更新</span></a>
    <a order_by="price" order_type="asc"><span>最低价格</span></a>
</div>
<div class="clear h10"></div>
<div class="w100 whitebg oh" id="box">
    {{--异步书本--}}
</div>
<p class="loading"><span>正在加载...</span></p>
@include('layouts._footer')

@endsection
@section('script')
<script type="text/javascript">
    eval('slidingCheckTit({{ Request::input('index', 0) }},"#slidingtit","menu","p","sel");');
    //参数依次为：当前选中索引、外层id、子集标签、孙子级标签，选中状态样式class
    var search_data = {'category_id':'{{ Request::input('category_id', 0) }}', 'orderBy':'updated_at', 'orderType':'desc', 'page':1};
    var _lock = false;
    function loadData(){
        var _count = $('#box').find('a').length;
        var _page = Math.ceil(_count / 6) + 1;
        if(_page == 0){
            _page = 1;
        }
        search_data.page = _page;
        $('.loading span').html('正在加载...');
        _lock = true;
        $.ajax({
            url:'{{ route('books.index') }}',
            type:'get',
            data:search_data,
            success: function (data){
                _lock = false;
                if(data){
                    $('#box').append(data);
                }else{
                    $('.loading span').html('没有更多');
                }
            }
        })
    }
    $(window).scroll(function() {
        if ($(document).scrollTop() >= $(document).height() - $(window).height() - 200) {
            if(_lock === false){
                loadData();
            }
        }
    });
    loadData();
    $(function (){
        $('#order_box').find('a').click(function (){
            _this = $(this);
            _this.siblings('a').removeClass('sel02');
            _this.addClass('sel02');
            $('#box').html('');
            search_data.orderBy = _this.attr('order_by');
            search_data.orderType = _this.attr('order_type');
            loadData();
        });
    })
</script>
@stop

resources/views/books/my.blade.php
@extends('layouts.app')
@section('content')
<header class="comhead">
    <h2>我的发布</h2>
    <a href="{{ route('memberIndex') }}" class="back"></a>
    {{--<a href="#" class="a2">&nbsp;</a>--}}
</header>
<div class="comheadbg"></div>

<div class="slidingtit" id="slidingtit">
    <menu>
        <p><a href="{{ Request::url() }}?index=0">全部</a></p>
        @foreach ($statuses as $key => $status)
        <p><a href="{{ Request::url() }}?status={{ $status['id'] }}&index={{ $key + 1 }}">{{ $status['name'] }}</a></p>
        @endforeach
    </menu>
</div>
<div class="clear h10"></div>

@if(count($mybooks))
@foreach($mybooks as $book)
<div class="orderlist">
    <section class="prolist">
        <div class="box">
            <i style="background-image: url({{ $book->image }})"></i>
            <p class="p7 green">{{ $book->status_name }}</p>
            <p class="p1">{{ $book->name }}</p>
            <p class="p2">{{ $book->author }}<span>{{ $book->press }}</span></p>
            <p class="p8">
                <a href="{{ route('books.show_self', $book->id) }}" class="btn01">查看</a>
                @can('toggleShow', $book)
                    @if($book->is_show == 1)
                        <a onclick="toggleShow($(this), {{ $book->id }})" class="btn03">下架</a>
                    @else
                        <a onclick="toggleShow($(this), {{ $book->id }})" class="btn02">上架</a>
                    @endif
                @endcan
                {{--<a href="#" class="btn04">删除</a>--}}
            </p>
        </div>
    </section>
</div>
@endforeach

<p class="overend"><span>已查看完全部发布</span></p>
    @else
    <p class="overend"><span>暂无内容</span></p>
@endif
@endsection
@section('script')
<script type="text/javascript">
    eval('slidingCheckTit({{ Request::input('index', 0) }},"#slidingtit","menu","p","sel");');
    //参数依次为：当前选中索引、外层id、子集标签、孙子级标签，选中状态样式class
    var ajax_lock = false;
    function toggleShow(_this, _id){
        if(ajax_lock === false){
            ajax_lock = true;
            $.ajax({
                url:'{{ route('books.toggle_show') }}',
                data:{id:_id},
                success:function(data){
                    ajax_lock = false;
                    if(data.status === 1){
                        if(_this.hasClass('btn03')){
                            layer.msg('下架成功！不再展示');
                            _this.attr('class', 'btn02');
                            _this.html('上架');
                        }else{
                            layer.msg('上架成功！能够被其他人看到');
                            _this.attr('class', 'btn03');
                            _this.html('下架');
                        }
                    }
                }
            });
        }
    }
</script>
@endsection

resources/views/books/photo_clip.blade.php
@extends('layouts.app')
@section('css')
<style>
    body {
        margin: 0;
        text-align: center;
    }
    #clipArea {
        height: 7.5rem;
        width: 7.5rem;
    }
    #file {

    }

    .btn_group{
        padding-top: 0.5rem;
        display: inline-block;
    }

    #clipBtn {
        display: block;
        float: left;
        width: 2rem;
        height: 0.6rem;
        line-height: 0.6rem;
        text-align: center;
        border: 0.02rem solid #0cbf9f;
        background: #FFF;
        border-radius: 0.04rem;
    }


    .left_btn{
        display: block;
        margin-right: 0.8rem;
        float: left;
        width: 2rem;
        height: 0.6rem;
        line-height: 0.6rem;
        text-align: center;
        border: 0.02rem solid #0cbf9f;
        background: #FFF;
        border-radius: 0.04rem;
    }
    .left_btn input{
        width: 100%; height: 100%;
        display: block;
        opacity:0;
    }
</style>
@endsection

@section('content')
<div id="clipArea"></div>
<div class="btn_group">

    <label class="left_btn">
        选择
        <input type="file" id="file">
    </label>
    <button id="clipBtn">截取</button>

</div>
@endsection
@section('script')
<script src="{{ asset('js/app.js') }}"></script>
<script>
    var functionName = '{{ Request::query('fn') }}';

    var size = eval('{{ Request::query('size') }}');

    var percent = [];
    percent[0] = (size[0] / (size[0] + size[1])) * 100;
    percent[1] = (size[1] / (size[0] + size[1])) * 100;
    percent[0] = percent[0] + '%';
    percent[1] = percent[1] + '%';
    console.log(size);
    console.log(percent);

    var pc = new PhotoClip('#clipArea', {
        size: size,
//        type: Number|Array
//
//        截取框大小。
//当值为数字时，表示截取框为宽高都等于该值的正方形。
//当值为数组时，数组中索引[0]和[1]所对应的值分别表示宽和高。
//默认值为 [100,100]。
        adaptive: percent,
        // adaptive: percent,

//        type: String|Array
//
//        截取框自适应。设置该选项后，size 选项将会失效，此时 size 进用于计算截取框的宽高比例。
//当值为一个百分数字符串时，表示截取框的宽度百分比。
//当值为数组时，数组中索引 [0] 和 [1] 所对应的值分别表示宽和高的百分比。
//当宽或高有一项值未设置或值无效时，则该项会根据 size 选项中定义的宽高比例自适应。
//默认为 ''。
        outputSize: [0,0],
//        type: Number|Array
//
//        输出图像大小。
//当值为数字时，表示输出宽度，此时高度根据截取框比例自适应。
//当值为数组时，数组中索引 [0] 和 [1] 所对应的值分别表示宽和高，若宽或高有一项值无效，则会根据另一项等比自适应。
//默认值为[0,0]，表示输出图像原始大小。
        outputQuality: 1,
//        type: Number
//
//        图片输出质量，仅对 jpeg 格式的图片有效，取值 0 - 1，默认为0.8。
//    （这个质量并不是图片的最终质量，而是在经过 lrz 插件压缩后的基础上输出的质量。相当于 outputQuality * lrzOption.quality）

        file: '#file',
//        view: '#view',
        ok: '#clipBtn',
        //img: 'img/mm.jpg',
        loadStart: function() {
            //console.log('开始读取照片');
        },
        loadComplete: function() {
            // msg('图片载入完成');
        },
        done: function(dataURL) {
            //console.log(dataURL);
            eval("window.parent."+functionName+"(dataURL)");
            var index = parent.layer.getFrameIndex(window.name); //先得到当前iframe层的索引
            parent.layer.close(index); //再执行关闭
        },
        fail: function(msg) {
            alert(msg);
        }
    });



</script>
@endsection

resources/views/books/show.blade.php
@extends('layouts.app')
@section('body', '')
@section('content')
<header class="comhead">
    <h2>书本详情</h2>
    <a href="javascript:history.back()" class="back"></a>
</header>
<div class="comheadbg"></div>

<div id="box" class="bannerbox">
    <ul id="sum" class="bannersum">
        <li><img src="{{ $book->image }}" /></li>
    </ul>
    <p id="num" class="bannernum"></p>
</div><!--我是banner-->
{{--
<p class="bannerpage">
    <a href="javascript:void(0);" id="bannernlast">&nbsp;</a>
    <a href="javascript:void(0);" id="bannernnext">&nbsp;</a>
</p>


<script type="text/javascript">
    eval('indexBanner("#box","#sum","li",300,5000,"#num","span","sel","#bannernlast","#bannernnext");');//Banner，可以不写“上一页”“下一页”的id，eavl()方法保证在代码之后加载执行
</script>
--}}
<div class="bookinfo">
    <p class="p1">{{ $book->name }}</p>
    <p class="p2">{{ $book->author }}<span>{{ $book->press }}</span></p>
    <p class="p3">
        <span class="sp1" style="position: static;margin-right: 1.5rem;">{{ $book->published_at }}年出版</span>
        <span class="sp2">{{ $book->used_format }}</span>{{--<span class="sp3">34本</span>--}}
    </p>
    <p class="p4">{!! $book->description !!}</p>
</div>

<div class="clear h02"></div>
<div class="sellerinfo">
    <div class="box">
        <i style="background-image: url({{ $user->avatar }})"></i>
        <p class="p1">{{ $user->name }}</p> <p class="p2">学校：{{ $user->school->name }}</p>
    </div>
    <p class="p3">{{ $user->last_actived_at->diffForHumans() }} 活跃</p>
</div>

<div class="clear h02"></div>

<div class="clear h10"></div>
<footer class="orderfoot">
    <p class="p1">应付：<span>￥{{ $book->price }}</span></p>
    @can('buy', $book)
    <form action="{{ route('order.create', $book) }}" >
        <input type="submit" value="立即购买" class="sub01" />
    </form>
        @else
        <a href="{{ route('passport.login') }}" class="sub01">请先登录</a>
    @endcan
</footer>
@endsection

resources/views/books/show_self.blade.php
@extends('layouts.app')
@section('body', '')
@section('content')
<header class="comhead">
    <h2>我的发布</h2>
    <a href="{{ route('books.my') }}" class="back"></a>
    <span class="sp1">{{ $book->status_name }}</span>
</header>
<div class="comheadbg"></div>
@include('public._message')
<section class="rel_info">
    <a class="a1"><span>ISBN：</span>{{ $book->sn }}</a>
</section>
<section class="rel_img">
    <p class="img" style="background-image: url({{ $book->image }})"></p>
    <div class="box">
        <p><span>书名：</span><input type="text" class="text" value="{{ $book->name }}" readonly /></p>
        <p><span>作者：</span><input type="text" class="text" value="{{ $book->author }}" readonly/></p>
        <p><span>出版社：</span><input type="text" class="text text01" value="{{ $book->press }}" readonly/></p>
        <p><span>出版年份：</span><input type="text"  class="text text02" value="{{ $book->published_at }}" readonly/></p>
    </div>
</section>
<div class="clear h02"></div>
<section class="rel_info">
    <a class="a1"><span>新旧：</span>{{ $book->used_format }}</a>
    <a class="a1"><span>分类：</span>{{ $book->category->name }}</a>
    <p class="p1">
        <span>原价：</span><input type="text" class="text" value="{{ $book->original_price }}" readonly />
        <span>出售价：</span><input type="text" class="text" value="{{ $book->price }}" readonly />
    </p>
    <p class="p2">
        <span>书本描述：</span>
    </p>
    <div style="padding-right: 0.3rem;padding-bottom:0.5rem; height: auto;">{!! $book->description !!}</div>
</section>
<div class="clear h10"></div>
<div class="bookbtn">
    @can('update', $book)
    <a href="{{ route('books.edit', $book->id) }}" class="sub sub01">编辑</a>
    @endcan
    @can('destroy', $book)
    <form id="delete_form" action="{{ route('books.destroy', $book->id) }}" method="post" style="display: inline-block;width: 27%;">
        {{ csrf_field() }}
        {{ method_field('DELETE') }}
        <input type="button" onclick="layer.confirm('确认删除', function (){$('#delete_form').submit()})" value="删除" class="sub sub03" style="width: 100%;" />
    </form>
    @endcan
</div>
<div class="clear h02"></div>
@endsection