routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index')->name('index');
Route::get('memberIndex', 'IndexController@memberIndex')->name('memberIndex');
Route::get('setSchool/{id}', 'IndexController@setSchool')->name('setSchool');
Route::get('search', 'IndexController@search')->name('search');

//登录注册
Route::get('register', 'PassportController@showRegisterForm')->name('passport.register');
Route::post('register', 'PassportController@register')->name('passport.register');
Route::get('login', 'PassportController@showLoginForm')->name('passport.login');
Route::post('login', 'PassportController@login')->name('passport.login');
Route::get('logout', 'PassportController@logout')->name('passport.logout');
Route::get('forgot', 'PassportController@showForgotForm')->name('passport.forgot');
Route::post('forgot', 'PassportController@forgot')->name('passport.forgot');

//个人信息
Route::get('user', 'UserController@index')->name('user.index');
Route::prefix('user')->group(function (){
    Route::get('avatar', 'UserController@avatar')->name('user.avatar');
    Route::post('avatar', 'UserController@updateAvatar')->name('user.avatar');
    Route::get('name', 'UserController@name')->name('user.name');
    Route::post('name', 'UserController@updateName')->name('user.name');
    Route::post('gander', 'UserController@updateGender')->name('user.gender');
    Route::post('school', 'USerController@updateSchool')->name('user.school');
});

//书本
Route::get('books/list', 'BooksController@list')->name('books.list');
Route::get('books/my', 'BooksController@my')->name('books.my');
Route::post('upload_image', 'BooksController@uploadImage')->name('books.upload_image');
Route::get('books/show-self/{book}', 'BooksController@showSelf')->name('books.show_self');//注意此处是一个隐式绑定
Route::get('books/toggle_show', 'BooksController@toggleShow')->name('books.toggle_show');
Route::resource('books', 'BooksController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);
//前端图片裁剪
Route::get('photo_clip', 'BooksController@photo_clip')->name('photo_clip');

//订单
Route::prefix('order')->group(function (){
    Route::get('create/{book}', 'OrdersController@create')->name('order.create');
    Route::post('store', 'OrdersController@store')->name('order.store');
    //列表
    Route::get('index', 'OrdersController@index')->name('order.index');
    Route::get('seller/index', 'OrdersController@sellerIndex')->name('order.seller_index');
    //详情
    Route::get('show/{order}', 'OrdersController@show')->name('order.show');
    Route::get('seller/show/{order}', 'OrdersController@sellerShow')->name('order.seller_show');
    //操作
    Route::get('pay/{order}' ,'OrdersController@pay')->name('order.pay');//发起支付
    Route::get('fake_pay', 'OrdersController@fakePay')->name('order.fake_pay');//模拟支付成功
    Route::get('confirm/{order}', 'OrdersController@confirm')->name('order.confirm');//卖家确认
    Route::get('send/{order}', 'OrdersController@send')->name('order.send');//卖家送达
    Route::get('get/{order}', 'OrdersController@get')->name('order.get');//买家取书
    Route::get('cancel/{order}', 'OrdersController@cancel')->name('order.cancel');//买家取消
});

//消息
Route::resource('notifications', 'NotificationsController', ['only' => ['index']]);

//提现
Route::resource('transfers', 'TransfersController', ['only' => ['create', 'store']]);

//资金
Route::get('account', 'AccountsController@index')->name('account.index');
Route::get('account/logs', 'AccountsController@logs')->name('account.logs');

//文章
Route::get('article/{article}/show', 'ArticlesController@show')->name('article.show');

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use URL;

class Article extends Model
{

    protected $hidden = ['content'];

    public function scopeAlias($query, $alias){
        return $query
            ->where('alias', 'like', '%'.$alias.'%')
            ->where('is_show', 1)
            ->orderBy('sort', 'asc');
    }

    public function getLinkAttribute($key)
    {
        if($key === 0){
            return 'javascript:void(0);';
        }

        if(URL::isValidUrl($key)){
            return $key;
        }else{
            return route('article.show', $this);
        }
    }



}

resources/views/index/index.blade.php
@extends('layouts.app')

@section('content')
    @include('layouts._set_school')
    <header class="comhead">
        <p class="btn01" onclick="$('#set_school').show()">{{ isset($sessionSchool) ? $sessionSchool->name : '请选择'}}</p>
        <div class="box01" onclick="location.href='{{ route('search') }}?focus=1'">
            <input type="submit" value=" " class="sub" />
            <input type="search" value="" class="text" placeholder="输入关键词" readonly />
        </div>
    </header>
    <div class="comheadbg"></div>
    @include('public._message')
    <a href="{{ $banner->link }}" class="block w100"><img src="{{ $banner->image }}" class="w100 block" /></a>
    <section class="indexmenu">
        <a href="{{ route('books.list') }}?category=1&index=1" style="background-image: url(images/ico/index01.png)">课本教材</a>
        <a href="{{ route('books.list') }}?category=2&index=2" style="background-image: url(images/ico/index02.png)">课外读物</a>
        <a href="{{ route('books.list') }}?category=3&index=3" style="background-image: url(images/ico/index03.png)">考研书籍</a>
        <a href="{{ route('books.list') }}" style="background-image: url(images/ico/index04.png)">更多分类</a>
    </section>
    <div class="clear h02"></div>
@if($books)
    <div class="indexhot">
        <h2 class="indextit01"><span>平台好书推荐</span></h2>
        <section class="indexlist">
            @foreach ($books as $book)
            <a href="{{ route('books.show', $book->id) }}">
                <i style="background-image: url({{ $book->image }});"></i>
                <p class="p1">{{ $book->name }}</p>
                <p class="p2">￥{{ $book->price }}<span>￥{{ $book->original_price }}</span></p>
            </a>
            @endforeach
        </section>
        {{--<a href="#" class="more"><span>查看更多</span></a>--}}
    </div>
    <div class="clear h02"></div>
@endif
    {{--<div class="indexhot">
        <h2 class="indextit01"><span>好书推荐</span></h2>
        <section class="indexgood">
            <a class="a1" href="#" style="background-image: url(images/photo/img02.png)"></a>
            <a class="a2" href="#" style="background-image: url(images/photo/img03.png)"></a>
            <a class="a3" href="#" style="background-image: url(images/photo/img03.png)"></a>
        </section>
        <h2 class="indextit01"><span>特惠图书</span></h2>
        <section class="indexlist">
            <a href="#">
                <i style="background-image: url(images/photo/img01.png);"></i>
                <p class="p1">全日制大学教科书</p>
                <p class="p2">￥55.55<span>￥88.88</span></p>
            </a>
            <a href="#">
                <i style="background-image: url(images/photo/img01.png);"></i>
                <p class="p1">全日制大学教科书</p>
                <p class="p2">￥55.55<span>￥88.88</span></p>
            </a>
            <a href="#">
                <i style="background-image: url(images/photo/img01.png);"></i>
                <p class="p1">全日制大学教科书</p>
                <p class="p2">￥55.55<span>￥88.88</span></p>
            </a>
            <a href="#">
                <i style="background-image: url(images/photo/img01.png);"></i>
                <p class="p1">全日制大学教科书</p>
                <p class="p2">￥55.55<span>￥88.88</span></p>
            </a>
            <a href="#">
                <i style="background-image: url(images/photo/img01.png);"></i>
                <p class="p1">全日制大学教科书</p>
                <p class="p2">￥55.55<span>￥88.88</span></p>
            </a>
            <a href="#">
                <i style="background-image: url(images/photo/img01.png);"></i>
                <p class="p1">全日制大学教科书</p>
                <p class="p2">￥55.55<span>￥88.88</span></p>
            </a>
        </section>
        <a href="#" class="more"><span>查看更多</span></a>
    </div>--}}
    <a href="{{ $middle->link }}" class="block w100"><img src="{{ $middle->image }}" class="w100 block" /></a>
    <h2 class="indextit01" style="top: 0.2rem;"><span>最新发布</span></h2>
    <div class="w100 whitebg oh" id="box">
        {{--书本容器--}}
    </div>
    <p class="loading"><span>正在加载...</span></p>

    @include('layouts._footer')

@endsection
@section('script')
<script type="text/javascript">
    winCloseMyWin(".winbgclick");//关闭窗口

    var search_data = {'orderBy':'updated_at', 'orderType':'desc', 'page':1};
    var _lock = false;
    function loadData(){
        var _count = $('#box').find('a').length;
        var _page = Math.ceil(_count / 6) + 1;
        if(_page == 0){
            _page = 1;
        }
        search_data.page = _page;
        $('.loading span').html('正在加载...');
        _lock = true;
        $.ajax({
            url:'{{ route('books.index') }}',
            type:'get',
            data:search_data,
            success: function (data){
                _lock = false;
                if(data){
                    $('#box').append(data);
                }else{
                    $('.loading span').html('没有更多');
                }
            }
        })
    }
    $(window).scroll(function() {
        if ($(document).scrollTop() >= $(document).height() - $(window).height() - 200) {
            if(_lock === false){
                loadData();
            }
        }
    });
    loadData();


</script>
@endsection

resources/views/index/member_index.blade.php
@extends('layouts.app')

@section('content')
<div class="membertop">
    <section>
        <i style="background-image: url({{ $user->avatar }})" onclick="location.href='{{ route('user.index') }}'"></i>
        <p class="p1">{{ $user->name }}</p>
        @if($user->school_id)
            <p class="p2">学校：{{ $user->school->name }}</p>
        @else
            <p class="p2" onclick="location.href='{{ route('user.index') }}'"> 请设置学校 </p>
        @endif
        <p class="p3">已购买 {{ $userOrderCount }} &nbsp;&nbsp; 已卖出 {{ $sellerOrderCount }}</p>
        <a class="a1" href="{{ route('passport.logout') }}">退出登录</a>
    </section>
</div>
@include('public._message')
<div class="membermenu">
    <a href="{{ route('order.index') }}" class="a1">购书订单<span>查看全部</span></a>
    <section class="tabfix">
        <menu>
            @foreach($statuses as $status)
                @if($status['forUser'])
                <a href="{{ route('order.index') }}?status={{ $status['id'] }}">
                    <img src="images/ico/{{ $status['ico'] }}" />
                    <p>{{ $status['name'] }}</p>
                    @if(isset($orderStatusCount[$status['id']]))
                        <b @if($orderStatusCount[$status['id']] == 0)style="background: #999;"@endif>{{ $orderStatusCount[$status['id']] }}</b>
                    @endif
                </a>
                @endif
            @endforeach
        </menu>
    </section>
</div>

@if($hasSell > 0)
<div class="membermenu">
    <a href="{{ route('order.seller_index') }}" class="a1">售书订单<span>查看全部</span></a>
    <section class="tabfix">
        <menu>
            @foreach($statuses as $status)
                @if($status['forSeller'])
                    <a href="{{ route('order.seller_index') }}?status={{ $status['id'] }}">
                        <img src="images/ico/{{ $status['ico'] }}" />
                        <p>{{ $status['name'] }}</p>
                        @if(isset($orderStatusCount[$status['id']]))
                            <b @if($orderStatusCount[$status['id']] == 0)style="background: #999;"@endif>{{ $orderStatusCount[$status['id']] }}</b>
                        @endif
                    </a>
                @endif
            @endforeach
        </menu>
    </section>
</div>
@endif
<div class="clear h02"></div>
<div class="memberbox">
    <a href="{{ route('books.my') }}" class="memberbtn">
        <p><i style="background-image: url(images/ico/member05.png)"></i>我的发布</p>
    </a>
    {{--<a href="#" class="memberbtn">
        <p><i style="background-image: url(images/ico/member06.png)"></i>收到的订单</p>
    </a>--}}
    <a href="{{ route('account.index') }}" class="memberbtn">
        <p><i style="background-image: url(images/ico/member07.png)"></i>资金账户</p>
    </a>
    <a href="{{ $about->link }}" class="memberbtn">
        <p><i style="background-image: url(images/ico/member08.png)"></i>平台介绍</p>
    </a>
    <a href="{{ route('user.index') }}" class="memberbtn">
        <p><i style="background-image: url(images/ico/member09.png)"></i>个人设置</p>
    </a>
</div>

<div class="clear h02"></div>

@include('layouts._footer')
@stop