routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index')->name('index');
Route::get('memberIndex', 'IndexController@memberIndex')->name('memberIndex');
Route::get('setSchool/{id}', 'IndexController@setSchool')->name('setSchool');
Route::get('search', 'IndexController@search')->name('search');

//登录注册
Route::get('register', 'PassportController@showRegisterForm')->name('passport.register');
Route::post('register', 'PassportController@register')->name('passport.register');
Route::get('login', 'PassportController@showLoginForm')->name('passport.login');
Route::post('login', 'PassportController@login')->name('passport.login');
Route::get('logout', 'PassportController@logout')->name('passport.logout');
Route::get('forgot', 'PassportController@showForgotForm')->name('passport.forgot');
Route::post('forgot', 'PassportController@forgot')->name('passport.forgot');

//个人信息
Route::get('user', 'UserController@index')->name('user.index');
Route::prefix('user')->group(function (){
    Route::get('avatar', 'UserController@avatar')->name('user.avatar');
    Route::post('avatar', 'UserController@updateAvatar')->name('user.avatar');
    Route::get('name', 'UserController@name')->name('user.name');
    Route::post('name', 'UserController@updateName')->name('user.name');
    Route::post('gander', 'UserController@updateGender')->name('user.gender');
    Route::post('school', 'USerController@updateSchool')->name('user.school');
});

//书本
Route::get('books/list', 'BooksController@list')->name('books.list');
Route::get('books/my', 'BooksController@my')->name('books.my');
Route::post('upload_image', 'BooksController@uploadImage')->name('books.upload_image');
Route::get('books/show-self/{book}', 'BooksController@showSelf')->name('books.show_self');//注意此处是一个隐式绑定
Route::get('books/toggle_show', 'BooksController@toggleShow')->name('books.toggle_show');
Route::resource('books', 'BooksController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);
//前端图片裁剪
Route::get('photo_clip', 'BooksController@photo_clip')->name('photo_clip');

//订单
Route::prefix('order')->group(function (){
    Route::get('create/{book}', 'OrdersController@create')->name('order.create');
    Route::post('store', 'OrdersController@store')->name('order.store');
    //列表
    Route::get('index', 'OrdersController@index')->name('order.index');
    Route::get('seller/index', 'OrdersController@sellerIndex')->name('order.seller_index');
    //详情
    Route::get('show/{order}', 'OrdersController@show')->name('order.show');
    Route::get('seller/show/{order}', 'OrdersController@sellerShow')->name('order.seller_show');
    //操作
    Route::get('pay/{order}' ,'OrdersController@pay')->name('order.pay');//发起支付
    Route::get('fake_pay', 'OrdersController@fakePay')->name('order.fake_pay');//模拟支付成功
    Route::get('confirm/{order}', 'OrdersController@confirm')->name('order.confirm');//卖家确认
    Route::get('send/{order}', 'OrdersController@send')->name('order.send');//卖家送达
    Route::get('get/{order}', 'OrdersController@get')->name('order.get');//买家取书
    Route::get('cancel/{order}', 'OrdersController@cancel')->name('order.cancel');//买家取消
});

//消息
Route::resource('notifications', 'NotificationsController', ['only' => ['index']]);

//提现
Route::resource('transfers', 'TransfersController', ['only' => ['create', 'store']]);

//资金
Route::get('account', 'AccountsController@index')->name('account.index');
Route::get('account/logs', 'AccountsController@logs')->name('account.logs');

//文章
Route::get('article/{article}/show', 'ArticlesController@show')->name('article.show');

resources/views/layouts/_footer.blade.php
<!--底部浮动-->
<div class="footbg"></div>
<footer class="foottab">
    <div class="tabfix">
        <menu>
            <a class="{{ active_class(if_route('index'), 'sel')  }}" href="{{ route('index') }}"><span>首页</span></a>
            <a class="{{ active_class(if_route('books.list'), 'sel')  }}" href="{{ route('books.list') }}"><span>分类</span></a>
            <a class="{{ active_class(if_route('books.create'), 'sel')  }}" href="{{ route('books.create') }}"></a>
            <a class="{{ active_class(if_route('notifications.index'), 'sel') }}" href="{{ route('notifications.index') }}"><span>消息</span>@auth<b @if(Auth::user()->notification_count == 0)style="background: #999;"@endif>{{ Auth::user()->notification_count }}</b>@endauth</a>
            <a class="{{ active_class(if_route('memberIndex'), 'sel')  }}" href="{{ route('memberIndex') }}"><span>我的</span></a>
        </menu>
    </div>
</footer>

resources/views/layouts/_set_school.blade.php
<!--弹窗-->
<aside class="winbg" id="set_school" @if(!session()->has('school_id')) style="display: block;" @endif>
    <div class="winbgclick"></div>
    <div class="schoolcheck">
        <h2>选择您所在的学校</h2>
        <section>
            @foreach($schools as $school)
                <a href="{{ $school->setSchoolLink() }}" @if(session('school_id') == $school->id) class="sel" @endif >{{ $school->name }}</a>
            @endforeach
        </section>
    </div>
</aside>

resources/views/layouts/app.blade.php
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Language" content="zh-CN">
    <title>@yield('title', '淘书屋')</title>
    {{--<meta name="keywords" content="">--}}
    {{--<meta name="description" content="">--}}
    <meta name="viewport" content="initial-scale=1,maximum-scale=1,minimum-scale=1,user-scalable=no">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <!-- 可隐藏地址栏，仅针对IOS的Safari（注：IOS7.0版本以后，safari上已看不到效果） -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <!-- 仅针对IOS的Safari顶端状态条的样式（可选default/black/black-translucent ） -->
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="App-Config" content="fullscreen=yes,useHistoryState=yes,transition=yes">
    <meta content="yes" name="apple-mobile-web-app-capable">
    <meta content="yes" name="apple-touch-fullscreen">
    <!-- IOS中禁用将数字识别为电话号码/忽略Android平台中对邮箱地址的识别 -->
    <meta name="format-detection"content="telephone=no, email=no" />
    <!-- 启用360浏览器的极速模式(webkit) -->
    <meta name="renderer" content="webkit">
    <!-- 避免IE使用兼容模式 -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- 针对手持设备优化，主要是针对一些老的不识别viewport的浏览器，比如黑莓 -->
    <meta name="HandheldFriendly" content="true">
    <!-- 微软的老式浏览器 -->
    <meta name="MobileOptimized" content="320">
    <!-- uc强制竖屏 -->
    <meta name="screen-orientation" content="portrait">
    <!-- QQ强制竖屏 -->
    <meta name="x5-orientation" content="portrait">
    <!-- UC强制全屏 -->
    <meta name="full-screen" content="yes">
    <!-- QQ强制全屏 -->
    <!-- UC应用模式 -->
    <meta name="browsermode" content="application">
    <!-- QQ应用模式 -->
    <meta name="x5-page-mode" content="app">
    <!-- windows phone 点击无高光 -->
    <meta name="msapplication-tap-highlight" content="no">

    <link href="{{ asset('css/style.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('css/common.css') }}" rel="stylesheet" type="text/css" />
    @yield('css')
</head>
<body class="@yield('body', 'whitebg')">

    @yield('content')

    <script src="{{ asset('js/jquery-1.9.1.min.js') }}"></script>
    <script src="{{ asset('js/common.js') }}"></script>
    <script src="{{ asset('layer/layer.js') }}"></script>
    <script>
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        $(function (){
            $('button.close').click(function (){
                $(this).parents('section').remove();
            });
        });
        function lc(_url, _title){
            layer.confirm(_title, function (){
                location.href=_url;
            })
        }
    </script>
    @auth
        @if (app()->isLocal())
            @include('sudosu::user-selector')
        @endif
    @endauth

@yield('script')
</body>
</html>