routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index')->name('index');
Route::get('memberIndex', 'IndexController@memberIndex')->name('memberIndex');
Route::get('setSchool/{id}', 'IndexController@setSchool')->name('setSchool');
Route::get('search', 'IndexController@search')->name('search');

//登录注册
Route::get('register', 'PassportController@showRegisterForm')->name('passport.register');
Route::post('register', 'PassportController@register')->name('passport.register');
Route::get('login', 'PassportController@showLoginForm')->name('passport.login');
Route::post('login', 'PassportController@login')->name('passport.login');
Route::get('logout', 'PassportController@logout')->name('passport.logout');
Route::get('forgot', 'PassportController@showForgotForm')->name('passport.forgot');
Route::post('forgot', 'PassportController@forgot')->name('passport.forgot');

//个人信息
Route::get('user', 'UserController@index')->name('user.index');
Route::prefix('user')->group(function (){
    Route::get('avatar', 'UserController@avatar')->name('user.avatar');
    Route::post('avatar', 'UserController@updateAvatar')->name('user.avatar');
    Route::get('name', 'UserController@name')->name('user.name');
    Route::post('name', 'UserController@updateName')->name('user.name');
    Route::post('gander', 'UserController@updateGender')->name('user.gender');
    Route::post('school', 'USerController@updateSchool')->name('user.school');
});

//书本
Route::get('books/list', 'BooksController@list')->name('books.list');
Route::get('books/my', 'BooksController@my')->name('books.my');
Route::post('upload_image', 'BooksController@uploadImage')->name('books.upload_image');
Route::get('books/show-self/{book}', 'BooksController@showSelf')->name('books.show_self');//注意此处是一个隐式绑定
Route::get('books/toggle_show', 'BooksController@toggleShow')->name('books.toggle_show');
Route::resource('books', 'BooksController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);
//前端图片裁剪
Route::get('photo_clip', 'BooksController@photo_clip')->name('photo_clip');

//订单
Route::prefix('order')->group(function (){
    Route::get('create/{book}', 'OrdersController@create')->name('order.create');
    Route::post('store', 'OrdersController@store')->name('order.store');
    //列表
    Route::get('index', 'OrdersController@index')->name('order.index');
    Route::get('seller/index', 'OrdersController@sellerIndex')->name('order.seller_index');
    //详情
    Route::get('show/{order}', 'OrdersController@show')->name('order.show');
    Route::get('seller/show/{order}', 'OrdersController@sellerShow')->name('order.seller_show');
    //操作
    Route::get('pay/{order}' ,'OrdersController@pay')->name('order.pay');//发起支付
    Route::get('fake_pay', 'OrdersController@fakePay')->name('order.fake_pay');//模拟支付成功
    Route::get('confirm/{order}', 'OrdersController@confirm')->name('order.confirm');//卖家确认
    Route::get('send/{order}', 'OrdersController@send')->name('order.send');//卖家送达
    Route::get('get/{order}', 'OrdersController@get')->name('order.get');//买家取书
    Route::get('cancel/{order}', 'OrdersController@cancel')->name('order.cancel');//买家取消
});

//消息
Route::resource('notifications', 'NotificationsController', ['only' => ['index']]);

//提现
Route::resource('transfers', 'TransfersController', ['only' => ['create', 'store']]);

//资金
Route::get('account', 'AccountsController@index')->name('account.index');
Route::get('account/logs', 'AccountsController@logs')->name('account.logs');

//文章
Route::get('article/{article}/show', 'ArticlesController@show')->name('article.show');

app/Models/Order.php
<?php

namespace App\Models;

use App\Notifications\OrderConfirmed;
use App\Notifications\OrderFinish;
use App\Notifications\OrderPayed;
use App\Notifications\OrderSend;

class Order extends Model
{
    const OPERATOR_USER = 1;
    const OPERATOR_SELLER = 2;
    const OPERATOR_ADMIN = 3;
    const OPERATOR_SYSTEM = 4;

    protected $fillable = ['message' , 'commission_user', 'commission_system'];

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function seller(){
        return $this->belongsTo(User::class, 'seller_id');
    }

    public function book(){
        return $this->belongsTo(Book::class);
    }

    public function school(){
        return $this->belongsTo(School::class);
    }

    public function orderLogs(){
        return $this->hasMany(OrderLog::class);
    }

    public function getStatusNameAttribute()
    {
        $statuses = array_pluck(config('custom.order.status'), 'name', 'id');
        return $statuses[$this->status];
    }

    public function payLink(){
        return route('order.pay', $this->id);
    }

    public function userLink(){
        return route('order.show', $this->id);
    }

    public function sellerLink(){
        return route('order.seller_show', $this->id);
    }

    public function createSn(){
        return date('YmdHis', time()).random_int(10, 99);
    }

    public function log($operator){
        (new OrderLog())->log($this, $operator);
    }

    //创建订单
    public function createOrder(User $user ,Book $book, $message = null){
        $this->sn = $this->createSn();
        $this->message = $message;
        $this->book_id = $book->id;
        $this->seller_id = $book->user_id;
        $this->user_id = $user->id;
        $this->school_id = $book->school_id;
        $this->price = $book->price;
        $this->name = $book->name;
        $this->image = $book->image;
        $this->status = 1;
        $this->save();
        $this->log(self::OPERATOR_USER);
        return $this;
    }

    //付款成功
    public function payed($out_sn, $payed_at, $payed_amount){
        $this->status = 2;
        $this->payed_amount = $payed_amount;
        $this->payed_at = $payed_at;
        $this->out_sn = $out_sn;
        $this->save();
        $this->book->payed();
        $this->log(self::OPERATOR_USER);
        $this->seller->notify(new OrderPayed($this));
        return $this;
    }

    //订单确认
    public function confirm(){
        $this->status = 3;
        $this->save();
        $this->log(self::OPERATOR_SELLER);
        $this->user->notify(new OrderConfirmed($this));
        return $this;
    }

    //书本送达
    public function send(){
        $this->status = 4;
        $this->save();
        $this->log(self::OPERATOR_SELLER);
        $this->user->notify(new OrderSend($this));
        return $this;
    }

    //收货
    public function finish(){
        $this->status = 5;
        $this->save();
        $this->log(self::OPERATOR_USER);
        $this->user->notify(new OrderFinish($this));
        return $this;
    }

    public function commission(){
        //转账代码如下
        $commission = config('commission');
        $commission_user = $this->price * ( ( 100 - $commission ) / 100 );
        $commission_system = $this->price * ( $commission / 100 );
        $this->update(compact('commission_user', 'commission_system'));
        $this->seller->addBalance($commission_user, 1, $this->toArray());
    }

    //取消
    public function cancel($operator = self::OPERATOR_ADMIN){
        $this->status = 6;
        $this->save();
        $this->log($operator);
        return $this;
    }

    //失效
    public function out(){
        $this->status = 7;
        $this->save();
        $this->log(self::OPERATOR_SYSTEM);
        return $this;
    }
}

app/Models/OrderLog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Admin;

class OrderLog extends Model
{
    public $fillable = [''];

    public function order(){
        return $this->belongsTo(Order::class);
    }

    public function getNameAttribute()
    {
        $types = config('custom.order.logs');
        $types = array_pluck($types, 'name', 'id');
        return $types[$this->order_status];
    }

    public function getOperatorNameAttribute()
    {
        $operators = config('custom.order.operator');
        $operators = array_pluck($operators, 'name', 'id');
        return $operators[$this->operator];
    }

    public function log(Order $order, $operator){
        switch ($operator){
            case $order::OPERATOR_USER:$operator_id = $order->user_id;break;
            case $order::OPERATOR_SELLER:$operator_id = $order->seller_id;break;
            case $order::OPERATOR_ADMIN:$operator_id = Admin::user()->id;break;
            case $order::OPERATOR_SYSTEM:$operator_id = 0;break;
        }
        $this->order_id = $order->id;
        $this->order_status = $order->status;
        $this->operator = $operator;
        $this->operator_id = $operator_id;
        $this->save();
        return $this;
    }

}

app/Http/Controllers/OrdersController.php
<?php

namespace App\Http\Controllers;

use App\Models\Book;
use App\Models\Order;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;

class OrdersController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    //买家列表
	public function index(Request $request)
	{
	    $user = Auth::user();
	    $status = $request->status;
		$orders = $user->orders()
            ->when($status, function ($query) use ($status){
                return $query->where('status', $status);
            })
            ->orderBy('created_at', 'desc')
            ->with('seller')
            ->get();
		$statuses = config('custom.order.status');
		return view('orders.index', compact('orders', 'statuses'));
	}

	//卖家列表
	public function sellerIndex(Request $request){
        $user = Auth::user();
        $status = $request->status;
        $orders = $user->sellOrders()
            ->when($status, function ($query) use ($status){
                return $query->where('status', $status);
            })
            ->orderBy('created_at', 'desc')
            ->with('seller')
            ->get();
        $statuses = config('custom.order.status');
        return view('orders.seller_index', compact('orders', 'statuses'));
    }

    //买家详情
    public function show(Order $order)
    {
        $this->authorize('show', $order);
        $school = $order->school;
        $seller = $order->seller;
        $logs = $order->orderLogs;
        return view('orders.show', compact('order', 'school', 'seller', 'logs'));
    }

    //卖家详情
    public function sellerShow(Order $order){
        $this->authorize('seller_show', $order);
        $school = $order->school;
        $buyer = $order->user;
        $logs = $order->orderLogs;
        return view('orders.seller_show', compact('order', 'school', 'buyer', 'logs'));
    }

    //确认下单
	public function create(Order $order, Book $book)
	{
        $this->authorize('buy', $book);
        $school = $book->school;
        $seller = $book->user;
		return view('orders.create', compact('order', 'school', 'seller', 'book'));
	}

	//订单创建
	public function store(Request $request, Order $order)
	{
	    $this->validate($request, [
	        'book_id'=>'required|numeric',
            'message'=>'nullable|max:255',
        ]);
		$book_id = $request->book_id;
		$book = Book::findOrFail($book_id);
		$this->authorize('buy', $book);
        $order = $order->createOrder(Auth::user(), $book, $request->message);
        return redirect()->to($order->payLink());
	}

	//订单发起支付
	public function pay(Order $order){
        $this->authorize('pay', $order);
        return view('orders.pay', compact('order'));
    }

    //模拟支付
    public function fakePay(Request $request){
        if(config('order_fake_pay') != 'on')return abort(404);
        $order = Order::where('sn' ,$request->sn)->firstOrFail();
        $this->authorize('pay', $order);
        $order->payed($order->createSn(), Carbon::now()->toDateTimeString(), $order->price);
        return redirect()->to($order->userLink())->with('message', '支付成功');
    }

    //卖家确认
    public function confirm(Order $order){
        $this->authorize('confirm', $order);
        $order->confirm();
        return redirect()->to($order->sellerLink())->with('message', '订单已确认！');
    }

    //卖家送达
    public function send(Order $order){
        $this->authorize('send', $order);
        $order->send();
        return redirect()->to($order->sellerLink())->with('message', '书本已确认送达！');
    }

    //买家收货+转账
    public function get(Order $order){
        $this->authorize('get', $order);
        $order->finish();

        $order->commission();

        return redirect()->to($order->userLink())->with('message', '确认收货成功！');
    }

    //买家取消
    public function cancel(Order $order){
        $this->authorize('cancel', $order);
        $order->cancel($order::OPERATOR_USER);
        return redirect()->to($order->userLink())->with('message', '订单已取消！');
    }




}

resources/views/orders/create.blade.php
@extends('layouts.app')
@section('body', '')
@section('content')
<header class="comhead">
    <h2>创建订单</h2>
    <a href="javascript:history.back()" class="back"></a>
</header>
<div class="comheadbg"></div>



<img src="/images/address.png" class="w100 block" />
<a class="top_address">
    <span>取货</span>
    <p class="p1">{{ $school->depot }}</p>
</a>
<div class="clear h02"></div>

<div class="w100 whitebg oh">
    <div class="order_menu">
        <i style="background-image: url({{ $seller->avatar }})"></i>
        <span>{{ $seller->name }}</span>
        <p>{{ $seller->school->name }}</p>
    </div>
    <div class="clear"></div>
    <a class="prolist" href="javascript:void(0);">
        <div class="box">
            <i style="background-image: url({{ $book->image }})"></i>
            <p class="p1">{{ $book->name }}</p>
            <p class="p2">{{ $book->author }}<span>{{ $book->press }}</span></p>
            <p class="p4"> x 1</p>
            <p class="p5">￥{{ $book->price }}</p>
        </div>
    </a>
</div>
<div class="clear h02"></div>

<form action="{{ route('order.store') }}" method="post">
    {{ csrf_field() }}
    <input type="hidden" name="book_id" value="{{ $book->id }}">

<section class="order_btn">
    <a class="a1" href="javascript:void(0);">
        <span class="sp1">配送方式</span>
        <p>自取</p>
    </a>
    <div class="box">
        <span class="sp1">买家留言</span>
        <input type="text" placeholder="选填" class="text" name="message" />
    </div>
</section>
<div class="clear h02"></div>

<div class="clear h10"></div>
<footer class="orderfoot">
    <p class="p1">应付：<span>￥{{ $book->price }}</span></p>
    <input type="submit" value="立即下单" class="sub01" />
</footer>
</form>

@endsection

resources/views/orders/index.blade.php
@extends('layouts.app')
@section('body', '')
@section('content')
<header class="comhead">
    <h2>购书订单</h2>
    <a href="{{ route('memberIndex') }}" class="back"></a>
</header>
<div class="comheadbg"></div>

<div class="ordertit">
    <section>
        <a class="{{ active_class(if_query('status', null), 'sel') }}" href="{{ url()->current() }}">全部</a>
        @foreach($statuses as $status)
            @if($status['forUser'])
            <a class="{{ active_class(if_query('status', $status['id']), 'sel') }}" href="{{ url()->current() }}?status={{ $status['id'] }}">{{ $status['name'] }}</a>
            @endif
        @endforeach
    </section>
</div>
<div class="clear h10"></div>
@if(count($orders))
    @foreach($orders as $order)
        <div class="orderlist">
            <div class="order_menu">
                <i style="background-image: url({{ $order->seller->avatar }})"></i>
                <span>{{ $order->seller->name }}</span>
                <p class="p1">{{ $order->status_name }}</p>
            </div>
            <div class="clear"></div>
            <div class="prolist" href="{{ $order->userLink() }}">
                <div class="box">
                    <a class="img" href="{{ $order->userLink() }}" style="background-image: url({{ $order->image }})"></a>
                    <a href="{{ $order->userLink() }}" class="p1">{{ $order->name }}</a>
                    {{--<p class="p2">作者名字<span>人民教育出版社</span></p>--}}
                    <p class="p6 p9">订单号：{{ $order->sn }}</p>
                    <p class="p10">
                        @can('pay', $order)
                        <a class="btn01" href="{{ $order->payLink() }}">前往支付</a>
                        @endcan
                        @can('get', $order)
                        <a class="btn01" onclick="lc('{{ route('order.get', $order) }}', '请确认您已拿到书本？')">确认取书</a>
                        @endcan
                        @can('cancel', $order)
                        <a class="btn02" onclick="lc('{{ route('order.cancel', $order) }}', '您确认取消订单？')">取消订单</a>
                        @endcan
                    </p>
                </div>
            </div>
        </div>
    @endforeach
<p class="overend"><span>已查看完全部订单</span></p>
    @else
    <p class="overend"><span>暂无订单~</span></p>
@endif

@endsection

resources/views/orders/pay.blade.php
@extends('layouts.app')
@section('body', '')
@section('content')
<header class="comhead">
    <h2>在线支付</h2>
    <a href="javascript:history.back()" class="back"></a>
</header>
<div class="comheadbg"></div>

<p style="text-align: center; margin-top: .5rem;">您正在进行订单 {{ $order->sn }} 的支付操作</p>
<p style="text-align: center; margin-top: .5rem;">请在微信中完成支付</p>
<p style="text-align: center; margin-top: .5rem;">支付书本：{{ $order->name }}</p>
<p style="text-align: center; margin-top: .5rem;">支付金额：<span style="font-size: 0.36rem;color: #ff0084;">￥{{ $order->price }}</span></p>
@if(config('order_fake_pay') == 'on')
<form action="{{ route('order.fake_pay') }}">
    <input type="hidden" name="sn" value="{{ $order->sn }}">
    {{ csrf_field() }}
    <input type="submit" value="模拟付款" class="paysub" />
</form>
@endif
{{--<aside class="winbg" style="display: block;">
    <div class="winbgclick"></div>
    <div class="win_success">
        <section style="background-image: url(images/error.png)">
            <p>支付失败！</p>大学生英语四级考试
        </section>
        <a href="#">重新支付</a>
    </div>
</aside>

<aside class="winbg">
    <div class="winbgclick"></div>
    <div class="win_success">
        <section>
            <p>恭喜您！购买成功</p>量子烈学
        </section>
        <a href="#">返回首页</a>
    </div>
</aside>--}}
@endsection
@section('javascript')
<script type="text/javascript">
    //winCloseMyWin(".winbgclick");//关闭窗口
</script>
@endsection

resources/views/orders/seller_index.blade.php
@extends('layouts.app')
@section('body', '')
@section('content')
<header class="comhead">
    <h2>售书订单</h2>
    <a href="{{ route('memberIndex') }}" class="back"></a>
</header>
<div class="comheadbg"></div>

<div class="ordertit">
    <section>
        <a class="{{ active_class(if_query('status', null), 'sel') }}" href="{{ url()->current() }}">全部</a>
        @foreach($statuses as $status)
            @if($status['forSeller'])
            <a class="{{ active_class(if_query('status', $status['id']), 'sel') }}" href="{{ url()->current() }}?status={{ $status['id'] }}">{{ $status['name'] }}</a>
            @endif
        @endforeach
    </section>
</div>
<div class="clear h10"></div>
@if(count($orders))
    @foreach($orders as $order)
        <div class="orderlist">
            <div class="order_menu">
                <i style="background-image: url({{ $order->user->avatar }})"></i>
                <span>{{ $order->user->name }}</span>
                <p class="p1">{{ $order->status_name }}</p>
            </div>
            <div class="clear"></div>
            <div class="prolist" href="{{ $order->sellerLink() }}">
                <div class="box">
                    <a class="img" href="{{ $order->sellerLink() }}" style="background-image: url({{ $order->image }})"></a>
                    <a href="{{ $order->sellerLink() }}" class="p1">{{ $order->name }}</a>
                    {{--<p class="p2">作者名字<span>人民教育出版社</span></p>--}}
                    <p class="p6 p9">订单号：{{ $order->sn }}</p>
                    <p class="p10">
                        @can('confirm', $order)
                            <a class="btn01" href="{{ route('order.confirm', $order) }}">确认订单</a>
                        @endcan
                        @can('send', $order)
                            <a class="btn01" onclick="lc('{{ route('order.send', $order) }}', '请确认您已将书本送达？')">确认送达</a>
                        @endcan
                            {{--<a class="btn02" href="{{ route('order.cancel', $order) }}">取消订单</a>--}}
                    </p>
                </div>
            </div>
        </div>
    @endforeach
<p class="overend"><span>已查看完全部订单</span></p>
    @else
    <p class="overend"><span>暂无订单~</span></p>
@endif

@endsection

resources/views/orders/seller_show.blade.php
@extends('layouts.app')
@section('body', '')
@section('content')
    <header class="comhead">
        <h2>订单详情</h2>
        <a href="{{ route('order.seller_index') }}" class="back"></a>
    </header>
    <div class="comheadbg"></div>
    @include('public._message')
    <img src="/images/address.png" class="w100 block" />
    <a class="top_address">
        <span>送达</span>
        <p class="p1">{{ $school->depot }}</p>
    </a>
    <div class="clear h02"></div>

    <div class="w100 whitebg oh">
        <div class="order_menu">
            <i style="background-image: url({{ $buyer->avatar }})"></i>
            <span>{{ $buyer->name }}</span>
            <p>{{ $buyer->school->name }}</p>
        </div>
        <div class="clear"></div>
        <a class="prolist" href="javascript:void(0);">
            <div class="box">
                <i style="background-image: url({{ $order->image }})"></i>
                <p class="p1">{{ $order->name }}</p>
                {{--<p class="p2">作者名字<span>人民教育出版社</span></p>--}}
                <p class="p4"> x 1</p>
                {{--<p class="p5">￥{{ $order->price }}</p>--}}
            </div>
        </a>
    </div>

    <section class="order_btn">
        <div class="box">
            <span class="sp1">订单号：</span>
            <p class="p1">{{ $order->sn }}</p>
        </div>
        <div class="box">
            <span class="sp1">订单状态：</span>
            <p class="p1">{{ $order->status_name }}</p>
        </div>
        {{--<div class="box">
            <span class="sp1">配送时间</span>
            <p class="p1">2018-05-22</p>
        </div>--}}
        {{--<div class="box">
            <span class="sp1">配送点</span>
            <p class="p1 green">已送达</p>
        </div>--}}
        <div class="box">
            <span class="sp1">买家留言：</span>
        </div>
        <div class="box2">
            <p>{{ $order->message }}</p>
        </div>
    </section>
    <div class="clear h02"></div>

    <section class="order_btn">
        <div class="box">
            <span class="sp1">订单日志：</span>
        </div>
        <div class="box2">
            @if($logs)
                @foreach ($logs as $log)
                    <p>{{ $log->name }}<span>{{ $log->created_at->diffForHumans() }}-{{ $log->operator_name }}</span></p>
                @endforeach
            @endif
        </div>
    </section>

    <div class="clear h10"></div>
    <footer class="orderfoot">
        <p class="p1">订单金额：<span>￥{{ $order->price }}</span></p>
        @can('confirm', $order)
            <a href="{{ route('order.confirm', $order) }}" class="sub01">确认订单</a>
        @endcan
        @can('send', $order)
            <a onclick="lc('{{ route('order.send', $order) }}', '请确认您已将书本送达？')" class="sub01">确认送达</a>
        @endcan
    </footer>

@endsection

resources/views/orders/show.blade.php
@extends('layouts.app')
@section('body', '')
@section('content')
<header class="comhead">
    <h2>订单详情</h2>
    <a href="{{ route('order.index') }}" class="back"></a>
</header>
<div class="comheadbg"></div>
@include('public._message')
<img src="/images/address.png" class="w100 block" />
<a class="top_address">
    <span>取货</span>
    <p class="p1">{{ $school->depot }}</p>
</a>
<div class="clear h02"></div>

<div class="w100 whitebg oh">
    <div class="order_menu">
        <i style="background-image: url({{ $seller->avatar }})"></i>
        <span>{{ $seller->name }}</span>
        <p>{{ $seller->school->name }}</p>
    </div>
    <div class="clear"></div>
    <a class="prolist" href="javascript:void(0);">
        <div class="box">
            <i style="background-image: url({{ $order->image }})"></i>
            <p class="p1">{{ $order->name }}</p>
            {{--<p class="p2">作者名字<span>人民教育出版社</span></p>--}}
            <p class="p4"> x 1</p>
            {{--<p class="p5">￥{{ $order->price }}</p>--}}
        </div>
    </a>
</div>

<section class="order_btn">
    <div class="box">
        <span class="sp1">订单号：</span>
        <p class="p1">{{ $order->sn }}</p>
    </div>
    <div class="box">
        <span class="sp1">订单状态：</span>
        <p class="p1">{{ $order->status_name }}</p>
    </div>
    {{--<div class="box">
        <span class="sp1">配送时间</span>
        <p class="p1">2018-05-22</p>
    </div>--}}
    {{--<div class="box">
        <span class="sp1">配送点</span>
        <p class="p1 green">已送达</p>
    </div>--}}
    <div class="box">
        <span class="sp1">买家留言：</span>
    </div>
    <div class="box2">
        <p>{{ $order->message }}</p>
    </div>
</section>
<div class="clear h02"></div>

<section class="order_btn">
    <div class="box">
        <span class="sp1">订单日志：</span>
    </div>
    <div class="box2">
        @if($logs)
            @foreach ($logs as $log)
                <p>{{ $log->name }}<span>{{ $log->created_at->diffForHumans() }}-{{ $log->operator_name }}</span></p>
            @endforeach
        @endif
    </div>
</section>

<div class="clear h10"></div>
<footer class="orderfoot">
    <p class="p1">订单金额：<span>￥{{ $order->price }}</span></p>
    @can('pay', $order)
        <a href="{{ $order->payLink() }}" class="sub01">前往支付</a>
    @endcan
    @can('get', $order)
        <a onclick="lc('{{ route('order.get', $order) }}', '请确认您已拿到书本？')" class="sub01">确认取书</a>
    @endcan
    @can('cancel', $order)
        <a onclick="lc('{{ route('order.cancel', $order) }}', '您确认取消订单？')" class="sub02">取消订单</a>
    @endcan
</footer>

@endsection